[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ["py36", "py37", "py38"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_tests = "tests"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER", "TESTS"]

[tool.poetry]
name = "tvdb_api_client"
version = "0.2.0"
description = "A python client for TVDB rest API"
authors = [
    "Stephanos Kuma <spapanik21@gmail.com>",
]

license = "MIT"
readme = "README.md"
include = ["CHANGELOG.md"]

repository = "https://github.com/spapanik/tvdb_api_client"

keywords = ["tvdb", "imdb", "tv series"]
classifiers=[
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Intended Audience :: Developers",
]

[tool.poetry.dependencies]
python = "^3.6"

requests = "^2.0"

[tool.poetry.dev-dependencies]
black = {version = "*", allow-prereleases = true}
isort = "^4.3"

pytest = "^5.1"
pytest-cov = "^2.8"
coveralls = "^1.8"

ipython = "^7.8"
ipdb = "^0.12"

flake8 = "^3.7"
flake8-bugbear = "^19.8"
flake8-builtins = "^1.4"
flake8-comprehensions = "^3.1"
flake8-eradicate = "^0.2.3"
flake8-executable = "^2.0"
flake8-mutable = "^1.2"
flake8-tidy-imports = "^3.1"
